name: MY WORKFLOW
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    env:
      CI: true
    strategy:
      matrix:
        node-version: [20]
    runs-on: windows-latest
    steps:
      - name: Checkout
      - uses: actions/checkout
      - name: Use node ${{matrix.node-version}}
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version}}
      - run: npm install
      - run: npm run test