name: MY WORKFLOW

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      CI: true

    strategy:
      matrix:
        node-version:
          - 20

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: MongoDB in GitHub Actions
        uses: supercharge/mongodb-github-action@v1.10.0

      - name: Set MONGO_URL environment variable
        run: echo "MONGO_URL=$MONGO_URL" >> $GITHUB_ENV
        env:
          MONGO_URL: ${{ secrets.MONGO_URL }}

      - name: Run tests
        run: npm run test
