name: MY WORKFLOW
on:
  push:
    branches: [ main ]
  pull_request:
    branches:  [ main ]
jobs:
  build:
    env:
      CI: true
    strategy:
      matrix:
        node-version: [20]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version}}
      - run: npm install
      - name: MongoDB in GitHub Actions
        uses: supercharge/mongodb-github-action@v1.10.0   
      - name: Set MONGO_URL environment variable
        env:
          MONGO_URL: ${{ secrets.MONGO_URL }}
            run: echo "MONGO_URL=$MONGO_URL" >> $GITHUB_ENV   
      - run: npm run test